services:
  postgres:
    image: postgres:16-alpine
    container_name: cuantodolio_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cuantodolio
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cuantodolio_net

  redis:
    image: redis:7-alpine
    container_name: cuantodolio_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cuantodolio_net

volumes:
  postgres_data:
  redis_data:

networks:
  cuantodolio_net:
    driver: bridge